export const need = [
    {
        age: "2",
        repos: 4 ,
        socialisation: 4,
        jeux: 1,
        rencontres: 2,
        mastication: 4,
        eau: 1,
        flair: 2,
        escaliers: "interdit",
    },
    {
        age: "3",
        repos: 3,
        socialisation: 3,
        jeux: 1,
        rencontres: 3,
        mastication: 4,
        eau: 1,
        flair: 2,
        escaliers: "interdit",
    },
    {
        age: "4",
        repos: 3,
        socialisation: 3,
        jeux: 2,
        rencontres: 3,
        mastication: 4,
        eau: 2,
        flair: 3,
        escaliers: "interdit",
    },
    {
        age: "5",
        repos: 3,
        socialisation: 2,
        jeux: 2,
        rencontres: 4,
        mastication: 4,
        eau: 2,
        flair: 3,
        escaliers: "modéré",
    },
    {
        age: "6",
        repos: 3,
        socialisation: 2,
        jeux: 2,
        rencontres: 4,
        mastication: 3,
        eau: 2,
        flair: 3,
        escaliers: "autorisé",
    },
    {
        age: "12",
        repos: 2,
        socialisation: 1,
        jeux: 1,
        rencontres: 2,
        mastication: 2,
        eau: 3,
        flair: 4,
        escaliers: "autorisé",
    },
];
